import React, { Component } from 'react';

class Main extends Component{
	render(){
		return(
			<div>
			Hey this is the background of teh page, this should disappear
					Hey this is the background of teh page, this should disappear
							Hey this is the background of teh page, this should disappear
							Hey this is the background of teh page, this should disappear
					Hey this is the background of teh page, this should disappear
				Hey this is the background of teh page, this should disappear
			Hey this is the background of teh page, this should disappear
						Hey this is the background of teh page, this should disappear
					Hey this is the background of teh page, this should disappear
							Hey this is the background of teh page, this should disappear
							Hey this is the background of teh page, this should disappear
					Hey this is the background of teh page, this should disappear
				Hey this is the background of teh page, this should disappear
			Hey this is the background of teh page, this should disappear
						Hey this is the background of teh page, this should disappear
					Hey this is the background of teh page, this should disappear
							Hey this is the background of teh page, this should disappear
							Hey this is the background of teh page, this should disappear
					Hey this is the background of teh page, this should disappear
				Hey this is the background of teh page, this should disappear
			Hey this is the background of teh page, this should disappear
						Hey this is the background of teh page, this should disappear
					Hey this is the background of teh page, this should disappear
							Hey this is the background of teh page, this should disappear
							Hey this is the background of teh page, this should disappear
					Hey this is the background of teh page, this should disappear
				Hey this is the background of teh page, this should disappear
			Hey this is the background of teh page, this should disappear
						Hey this is the background of teh page, this should disappear
					Hey this is the background of teh page, this should disappear
							Hey this is the background of teh page, this should disappear
							Hey this is the background of teh page, this should disappear
					Hey this is the background of teh page, this should disappear
				Hey this is the background of teh page, this should disappear
			Hey this is the background of teh page, this should disappear
						Hey this is the background of teh page, this should disappear
					Hey this is the background of teh page, this should disappear
							Hey this is the background of teh page, this should disappear
							Hey this is the background of teh page, this should disappear
					Hey this is the background of teh page, this should disappear
				Hey this is the background of teh page, this should disappear
			Hey this is the background of teh page, this should disappear
						Hey this is the background of teh page, this should disappear
					Hey this is the background of teh page, this should disappear
							Hey this is the background of teh page, this should disappear
							Hey this is the background of teh page, this should disappear
					Hey this is the background of teh page, this should disappear
				Hey this is the background of teh page, this should disappear
			Hey this is the background of teh page, this should disappear

			Hey this is the background of teh page, this should disappear
					Hey this is the background of teh page, this should disappear
							Hey this is the background of teh page, this should disappear
							Hey this is the background of teh page, this should disappear
					Hey this is the background of teh page, this should disappear
				Hey this is the background of teh page, this should disappear
			Hey this is the background of teh page, this should disappear
						Hey this is the background of teh page, this should disappear
					Hey this is the background of teh page, this should disappear
							Hey this is the background of teh page, this should disappear
							Hey this is the background of teh page, this should disappear
					Hey this is the background of teh page, this should disappear
				Hey this is the background of teh page, this should disappear
			Hey this is the background of teh page, this should disappear
						Hey this is the background of teh page, this should disappear
					Hey this is the background of teh page, this should disappear
							Hey this is the background of teh page, this should disappear
							Hey this is the background of teh page, this should disappear
					Hey this is the background of teh page, this should disappear
				Hey this is the background of teh page, this should disappear
			Hey this is the background of teh page, this should disappear
						Hey this is the background of teh page, this should disappear
					Hey this is the background of teh page, this should disappear
							Hey this is the background of teh page, this should disappear
							Hey this is the background of teh page, this should disappear
					Hey this is the background of teh page, this should disappear
				Hey this is the background of teh page, this should disappear
			Hey this is the background of teh page, this should disappear
						Hey this is the background of teh page, this should disappear
					Hey this is the background of teh page, this should disappear
							Hey this is the background of teh page, this should disappear
							Hey this is the background of teh page, this should disappear
					Hey this is the background of teh page, this should disappear
				Hey this is the background of teh page, this should disappear
			Hey this is the background of teh page, this should disappear
						Hey this is the background of teh page, this should disappear
					Hey this is the background of teh page, this should disappear
							Hey this is the background of teh page, this should disappear
							Hey this is the background of teh page, this should disappear
					Hey this is the background of teh page, this should disappear
				Hey this is the background of teh page, this should disappear
			Hey this is the background of teh page, this should disappear
						Hey this is the background of teh page, this should disappear
					Hey this is the background of teh page, this should disappear
							Hey this is the background of teh page, this should disappear
							Hey this is the background of teh page, this should disappear
					Hey this is the background of teh page, this should disappear
				Hey this is the background of teh page, this should disappear
			Hey this is the background of teh page, this should disappear

			Hey this is the background of teh page, this should disappear
					Hey this is the background of teh page, this should disappear
							Hey this is the background of teh page, this should disappear
							Hey this is the background of teh page, this should disappear
					Hey this is the background of teh page, this should disappear
				Hey this is the background of teh page, this should disappear
			Hey this is the background of teh page, this should disappear
						Hey this is the background of teh page, this should disappear
					Hey this is the background of teh page, this should disappear
							Hey this is the background of teh page, this should disappear
							Hey this is the background of teh page, this should disappear
					Hey this is the background of teh page, this should disappear
				Hey this is the background of teh page, this should disappear
			Hey this is the background of teh page, this should disappear
						Hey this is the background of teh page, this should disappear
					Hey this is the background of teh page, this should disappear
							Hey this is the background of teh page, this should disappear
							Hey this is the background of teh page, this should disappear
					Hey this is the background of teh page, this should disappear
				Hey this is the background of teh page, this should disappear
			Hey this is the background of teh page, this should disappear
						Hey this is the background of teh page, this should disappear
					Hey this is the background of teh page, this should disappear
							Hey this is the background of teh page, this should disappear
							Hey this is the background of teh page, this should disappear
					Hey this is the background of teh page, this should disappear
				Hey this is the background of teh page, this should disappear
			Hey this is the background of teh page, this should disappear
						Hey this is the background of teh page, this should disappear
					Hey this is the background of teh page, this should disappear
							Hey this is the background of teh page, this should disappear
							Hey this is the background of teh page, this should disappear
					Hey this is the background of teh page, this should disappear
				Hey this is the background of teh page, this should disappear
			Hey this is the background of teh page, this should disappear
						Hey this is the background of teh page, this should disappear
					Hey this is the background of teh page, this should disappear
							Hey this is the background of teh page, this should disappear
							Hey this is the background of teh page, this should disappear
					Hey this is the background of teh page, this should disappear
				Hey this is the background of teh page, this should disappear
			Hey this is the background of teh page, this should disappear
						Hey this is the background of teh page, this should disappear
					Hey this is the background of teh page, this should disappear
							Hey this is the background of teh page, this should disappear
							Hey this is the background of teh page, this should disappear
					Hey this is the background of teh page, this should disappear
				Hey this is the background of teh page, this should disappear
			Hey this is the background of teh page, this should disappear			

			</div>
		);
	}
}

export default Main; 